### ISSUE TITLE
Download fails on files with '#' in name

### ISSUE THREAD

**Issue by kmitcham** [AllenInstitute/biofile-finder#104]
As a user, I'd like to be able to download the 10 files in fms that have '#' in the name using FE.

I'd also like to download the other files that might have html-active characters in the name.

This came up with SaraC trying to download  20191111_M02_001_#24_z14to60_8bit_scalebar10.avi  ( File id: 1a0a8a56d58a4a21923f13929ccaf91c ) using the explorer, but I was able to get her the file via cp from Vast, so she wasn't blocked for long.

**Comment by kmitcham** [comment]
Comments from slack:
Looks like the request the loadbalancer (Nginx) saw was this:
GET /labkey/fmsfiles/image/allen/programs/allencell/data/proj0/91c/caf/29c/139/23f/219/a4a/d58/a56/0a8/1a/20191111_M02_001_ HTTP/1.1
andrewl
:house_with_garden:  [20 minutes ago](https://allencellscience.slack.com/archives/C021CEY96LD/p1715895156043749?thread_ts=1715893682.688139&cid=C021CEY96LD)
Looks like FE just needs to escape the # - this request through the loadbalancer works: [http://aics.corp.alleninstitute.org/labkey/fmsfiles/image/allen/programs/allencell/data/pr[…]/1a/20191111_M02_001_%2324_z14to60_8bit_scalebar10.avi](http://aics.corp.alleninstitute.org/labkey/fmsfiles/image/allen/programs/allencell/data/proj0/91c/caf/29c/139/23f/219/a4a/d58/a56/0a8/1a/20191111_M02_001_%2324_z14to60_8bit_scalebar10.avi)

**Comment by SeanLeRoy** [comment]
Working as of now
