### ISSUE TITLE
Reduce network calls for zarr rendering

### ISSUE THREAD

**Issue by BrianWhitneyAI** [AllenInstitute/biofile-finder#162]
Works for me locally! Below are thoughts that don't need to be addressed rn: 

My only concern is that this requires a lot of network calls at once, including multiple expected non-breaking 404s per file. The main build up is on initial load, which makes sense, but also happens if you just click away from a file that's already loaded once and click back into it, so they can multiply quickly and cause some slowness. I'm wondering if there is some way we can cache...something?, but not sure if that's a realistic possibility.

Here's the network log after clicking into one file after clearing logs from initial page load:
<img width="531" alt="Screenshot 2024-07-03 at 5 07 51 PM" src="https://github.com/AllenInstitute/aics-fms-file-explorer-app/assets/24441706/dccdb789-fa19-40a4-b825-368e31870942">

_Originally posted by @aswallace in https://github.com/AllenInstitute/aics-fms-file-explorer-app/pull/143#pullrequestreview-2157651876_

**Comment by BrianWhitneyAI** [comment]
A portion of this is because the zarrita package makes calls for files that do not exist, searching for additional context. "zarr.json" for example.

**Comment by SeanLeRoy** [comment]
This seems like a performance issue with zarrita not us, closing for now since it seems like a non-issue for now
