### ISSUE TITLE
Styling needed for filter values modals

### ISSUE THREAD

**Issue by lynwilhelm** [AllenInstitute/biofile-finder#195]
Styling is needed for filter values modals that present a range. We are aware so far of instances of date range and numerical range, but we may want to click around to see if there are other types that could use love and be a part of this piece of work. Also, check with devs if they also want to include date picker in this. Can we easily change to a dark theme that matches our styling?

## Anya edits:
(We also need to incorporate the any/none radio-- should I make a separate ticket or integrate that into this one?) 

The **current** filter modals are: 
- Basic search box
  - technically only needs to be used for a few specific fields where we can't show the users all the values (e.g., file name, file path -- there's too many values)
- Select from a list of values (has its own search bar)
  - current default if there are fewer than 100 options, but we've discussed making it the default for any field where we know the values regardless of how many there are (e.g., 1000 values) since they can search the list
- Date range
- Numerical range
   - For this and date, when there are only a few values, we discussed allowing the user to use the pick from a list modal instead --> QUESTION: how many is an appropriate number of values to show in a list vs use the range modal?

Screenshots of current modals: 

### Searchbox
- Needs fuzzy & exact option --> toggle is not currently present on deployed versions
<img width="708" alt="image" src="https://github.com/user-attachments/assets/766ee9a0-4e42-4717-8f87-f2428d528b11">

### Select from a list
<img width="707" alt="image" src="https://github.com/user-attachments/assets/dd7589fd-47b5-4e50-8f9c-15959267ad02">

### Numerical range
![Screenshot 2024-08-06 at 3 22 11 PM](https://github.com/user-attachments/assets/3fdae267-1dd2-4f6b-b39c-a9f9b08b53a2)

### Date range
![Screenshot 2024-08-06 at 3 22 23 PM](https://github.com/user-attachments/assets/a61c4dec-4b31-4ea2-88ee-3f23a842a953)
![Screenshot 2024-08-06 at 3 48 13 PM](https://github.com/user-attachments/assets/7bff83c5-6653-432b-89ef-7f4f380bfa63)

**Comment by SeanLeRoy** [comment]
When selecting dates I think it would be useful to have "quick-select" options like a buttons for "Last year", "Last month", "Last 6 months" - users found that useful in the old finder UI

**Comment by aswallace** [comment]
We also need to integrate the any/none/specific values radio and determine what should display (if anything) when any or none are selected, e.g.,
<img width="709" alt="Screenshot 2024-08-21 at 3 19 31 PM" src="https://github.com/user-attachments/assets/fa16597c-cf2c-406b-95b6-76a85018d6e5">

**Comment by lynwilhelm** [comment]
@aswallace

URL so you can see spacing and hover styles: https://www.figma.com/design/oNQvOAK11YINcbPvNmkgwO/Public-File-Explorer?node-id=1529-17808&t=SiAQaJdjcIXpXpII-0

Also here is a screen shot for quick reference
![Screenshot 2024-08-26 at 4 26 06 PM](https://github.com/user-attachments/assets/bd566dd3-ec61-469b-8e79-c4308b767fd5)
