### ISSUE TITLE
Improve styling and behavior of multiselect of lists

### ISSUE THREAD

**Issue by lynwilhelm** [AllenInstitute/biofile-finder#201]
### Description
There is currently only default styling on select all and clear all affordances at the top of lists. We should define what is should be. Some thoughts are:

- Should they maybe not look like buttons at all (checkbox and styled "clear all" instead?) or should we come up with a special button style for these that have clearer meaning?
- Should "clear all" show at all before multiple are selected? Or what good styling can we provide for a disabled state? (A disabled state it does help the user discover multiselect capability)

***
_Below to be filled out by UX during kickoff Q&A to the best of current understanding_

### Size
_Effort level (xs, sm, m, lg, xl)_
**XS**
### Scope
_What will we do? What will we NOT do?_

### User needs statement(s)
As a _[type of user]_, I need/want to _[action(s)]_, so that I can _[goal]_.

### Additional notes
_Knowns/unknowns, stakeholders, time/dependency considerations, deliverables_

Examples in current UI:
<img width="891" alt="Screenshot 2024-08-07 at 2 30 38 PM" src="https://github.com/user-attachments/assets/61ff9d1a-82dd-4b0b-bcf0-071cf0d4cc34">
<img width="673" alt="Screenshot 2024-08-07 at 2 31 45 PM" src="https://github.com/user-attachments/assets/1ea4efa0-ad8a-4b09-bc24-0219e93f0a6f">

**Comment by SeanLeRoy** [comment]
I believe this pre-dates UX work around filtering when we added the "has any value" and "has no value" stuff. Re-open if you still think there is work to do @lynwilhelm
