### ISSUE TITLE
Replace images on homepage

### ISSUE THREAD

**Issue by lynwilhelm** [AllenInstitute/biofile-finder#207]
Graham requested some slightly more refined screenshots for the homepage guidance. They are too small and a bit noisy, including some distracting UI that is not pertinent to the text.

I will be reproducing the screenshots and using Photoshop to blur the backgrounds of some photos that need that treatment.

**Implementation notes:**

1. Please replace carousel images. (688x300 max size). This is related to some work I previously requested, which was to add a couple things to the carousel to improve the look/behavior.
2. Yoi will also need to update the content for the first image to reflect the new group by options! (Structure, followed by plate barcode)

**Comment by lynwilhelm** [comment]
Here are the image to replace existing. @SeanLeRoy you may want to check them out.

[homepage_images.zip](https://github.com/user-attachments/files/16642520/homepage_images.zip)

**Comment by SuyashShukla0007** [comment]
is it open

**Comment by aswallace** [comment]
It's also been requested that we add clickable arrows to make it clearer that there are more images per feature and shrink the circles slightly ([noted in the Google doc](https://docs.google.com/document/d/1QP_xT7IZOuLjgaHyK2gletNUK1ybCt7B_ayOG34H0zU/edit?disco=AAABR8Jd2wI))
