### ISSUE TITLE
Shorten URL

### ISSUE THREAD

**Issue by SeanLeRoy** [AllenInstitute/biofile-finder#221]
Currently the full URL to a dataset can get REALLY long (see below), is there any way we could hash or do something to make this shorter??

https://biofile-finder.allencell.org/app?source=%7B%22name%22%3A%22imaging_and_segmentation_data.csv+%288%2F15%2F2024+4%3A26%3A03+PM%29%22%2C%22type%22%3A%22csv%22%2C%22uri%22%3A%22https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Femt_timelapse_dataset%2Fmanifests%2Fimaging_and_segmentation_data.csv%3FversionId%3DWmTjARBNL4rNJhV4N7YFYr2dKHWlCHwc%22%7D&sourceMetadata=%7B%22name%22%3A%22Imaging_and_segmentation_data_column_description.csv+%288%2F15%2F2024+4%3A26%3A02+PM%29%22%2C%22type%22%3A%22csv%22%2C%22uri%22%3A%22https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Femt_timelapse_dataset%2Fmanifests%2FImaging_and_segmentation_data_column_description.csv%3FversionId%3D.bmbr.UUT06F9nupeuwxVBYuTMyKyYu6%22%7D

**Comment by toloudis** [comment]
I'm interested in what you come up with here. We are having similar issues with volume viewer saved links.  I wonder if a url shortener service is something we could even consider.

**Comment by SeanLeRoy** [comment]
I tried something quick using base64 encoding from poking on the web a bit but it seems that is only useful with links even bigger than ours so it made it worse. Need to try some other stuff out though

**Comment by toloudis** [comment]
Cameron investigated base64 and we quickly found that it can actually lengthen strings when the unencoded data is just mainly letters and numbers.  Good for encoding binary to url but not so good for compression.  I also found a js library that can LZ compress a string (`lz-string`) and put that in the url but it was not useful for our volume viewer urls.
