### ISSUE TITLE
Download zarrs from AICS FMS

### ISSUE THREAD

**Issue by BrianWhitneyAI** [AllenInstitute/biofile-finder#244]
We have decided to forgo individual local file tracking for now. In the situation that we use a /allen path and want to download locally we should use the FmsFile class's logic for determining cloud paths for all zarrs so that the existing download tracking functions correctly. This might prove more complicated as right now we do not support download paths for paths like `s3://allencell/`

_Originally posted by @BrianWhitneyAI in https://github.com/AllenInstitute/biofile-finder/issues/243#issuecomment-2368907369_

**Comment by BrianWhitneyAI** [comment]
Right now we only support S3 downloads and local copying on desktop. The current download path we are using allows for rendering thumbnails but not for download (since it doesnt meet our current S3 method). The cloudpaths we have for those files are permission blocked so we cant use that for download either. If we want to support download from AICS FMS we need to either change permissions of the cloudpaths or look into downloading other formatted paths (RN its a http). This could just point to a s3 file and be easy but would be another step.

**Comment by SeanLeRoy** [comment]
#205 should close this
