### ISSUE TITLE
CSV file format

### ISSUE THREAD

**Issue by fcollman** [AllenInstitute/biofile-finder#272]
I was trying to use the tool with CSVs from recent brain science released genetic tools atlas, but it never seems to show me anything after i upload the CSV and i'm not sure why... all the images are in public locations in ZARR format in S3. 

Here are the example CSVs i used, from most comprehensive to more limited examples and columns. 

[Updated_Specimen_Metadata_one.csv](https://github.com/user-attachments/files/17351110/Updated_Specimen_Metadata_one.csv)
[Updated_Specimen_Metadata_small.csv](https://github.com/user-attachments/files/17351111/Updated_Specimen_Metadata_small.csv)
[Updated_Specimen_Metadata_with_ome-zarr_locations.csv](https://github.com/user-attachments/files/17351112/Updated_Specimen_Metadata_with_ome-zarr_locations.csv)

**Comment by fcollman** [comment]
looking at the developer console, i saw the error "File path" must exist, and now poking around I see that under "see more" it said that I had to have some specific columns to make certain things work.  

There should a validation error showing the user what they are going to get wrong, and the basic statement that you need any csv with the column called "File Path" to make this work. Better would be a dialog that lets you pick the column name that is "File Path" if the file path column does not exist. 

Right now the page kind of pulses  with the correct number of rows that giving me the impression that it is "loading" when in fact there was an error.

**Comment by fcollman** [comment]
The File Path also seems like it needs to be an http:// location and not an s3:// location in order to make the image viewer kind of load something..

For example.. s3://allen-genetic-tools/tissuecyte/1212211740/ome-zarr/
will not load in the 3d image viewer..

but https://allen-genetic-tools.s3.amazonaws.com/tissuecyte/1212211740/ome-zarr does sort of load but then displays nothing..
https://volumeviewer.allencell.org/viewer?url=https%3A%2F%2Fallen-genetic-tools.s3.amazonaws.com%2Ftissuecyte%2F1212211740%2Fome-zarr%2F

I'll cross post this on the 3d cell viewer, but it seems the instructions for what the "file path" needs to be are not precise enough.

Also, i discovered, after renaming the csv column to "File Path" that because the CSV had a few rows without image paths that it wouldn't load any of the rows and also didn't give me an error except in the developer console so i had to filter those rows out myself.

**Comment by toloudis** [comment]
We will add s3 and gc url support to volume viewer too, soon.  We can do that fairly quickly with a string replacement.
