### ISSUE TITLE
Minor style fixes

### ISSUE THREAD

**Issue by aswallace** [AllenInstitute/biofile-finder#287]
List of style fixes from [this document](https://docs.google.com/document/d/1QP_xT7IZOuLjgaHyK2gletNUK1ybCt7B_ayOG34H0zU) that haven't been completed yet.
Most of these are small & should be quick fixes. Details and screenshots are in doc

- [x] Help menu dropdown items are 14px and should be 16px. Also, there is CSS causing little white corners to show.
- [x] Use a different icon for “View Datasets” button on home page
- [ ] ~Discover features items on home: Either add autoplay or left/right buttons with (e.g.) 1/4~ (Skipping since overlaps with #207 )
- [x] Open-source datasets: related publication link should open in new tab
- [x] "Active" style for query naming input should be bright aqua (match search box outline styling)
- [x] Check line spacing for text & subheaders in new data source modal
- [x] Swap caret direction for collapsed query states
- [x] Check fill/size for icons in queries
- [x] Left panel is not using the intended icon for “collapse”
- [x] Add box shadow to individual queries
- [x] Check spacing on left and right panels (see doc/figma for details)
- [x] All buttons (e.g., download/open) should have left/right padding of 19px at all times
- [x] Check if text in last file in list is still cut off
- [ ] ~Agave menu item styling~ (This is covered by #284 )
- [x] Remove icon from file types (csv, json, parquet)
- [x] Change "New query" in collapsed left panel to "Open query panel" or similar, fix icon, change background & font weight
- [x] Various thumbnail svg issues
    - File names on image grid are not white. 
    -  Not rendering border radius
    - Svg looks off-center
    - Svg color conflicts with background when selected
    - Label needs more padding
- [x] Row styling does not extend all the way across

**Comment by SuyashShukla0007** [comment]
can i work on this
